name: nx-fullstack-starter
services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    volumes:
      - starter-postgresdb:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - internal-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRESDB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    depends_on:
      postgresdb:
        condition: service_healthy
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      - NODE_PORT=${NODE_PORT:-3200}
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_PRODUCTION=${NODE_PRODUCTION:-true}
      - POSTGRESDB_USER=${POSTGRESDB_USER}
      - POSTGRESDB_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRESDB_DATABASE=${POSTGRESDB_DATABASE}
      - POSTGRESDB_PORT=${POSTGRESDB_PORT:-5432}
      - POSTGRESDB_HOST=postgresdb
      - INTERNAL_JWT_PUBLIC_KEY=${INTERNAL_JWT_PUBLIC_KEY}
      - HASH_SALT_ROUNDS=${HASH_SALT_ROUNDS:-10}
      - NODE_UPLOAD_FILES=${NODE_UPLOAD_FILES:-uploads}
    networks:
      - internal-network
    volumes:
      - upload_files:/home/app-api/${NODE_UPLOAD_FILES:-uploads}
      - tmp:/tmp

  gateway:
    depends_on:
      - api
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT:-3100}
      - NODE_ENV=${NODE_ENV:-production}
      - API_BASE_URL=http://api:${NODE_PORT:-3200}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-4h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-8h}
      - INTERNAL_JWT_PRIVATE_KEY=${INTERNAL_JWT_PRIVATE_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - SERVICE_FQDN_GATEWAY=${SERVICE_FQDN_GATEWAY}
    ports:
      - '${GATEWAY_PORT:-3100}'
    networks:
      - edge-network
      - internal-network

  front:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    container_name: front
    depends_on:
      - gateway
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_FRONT=${SERVICE_FQDN_FRONT}
    ports:
      - '${FRONT_PORT:-80}'
    networks:
      - edge-network

volumes:
  starter-postgresdb:
  upload_files:
  tmp:

networks:
  edge-network:
  internal-network:
    internal: true
